### ISSUE TITLE
Dart Support

### ISSUE THREAD

**Issue by LaksCastro** [oppsec/Ozzy#2]
Is there any way to make this theme compatible with Dart?

I really liked the theme, but when I opened it in a `.dart` file, the result is this:

![a](https://user-images.githubusercontent.com/51419598/92181753-efb31f80-ee41-11ea-9f62-25ae1b6a082e.PNG)

Congratulations on the work, very good this theme

Thanks,
LaksCastro

**Comment by oppsec** [comment]
Yes of course, I'll give a special attention to Dart, thanks for opening a Issue. 😄
